### ISSUE TITLE
Prepare for rename to setup-beam

### ISSUE THREAD

**Issue by starbelly** [erlef/setup-elixir#20] opened 2021-03-26 03:41 UTC
After the setup erlang PR is merged (which I'm not linking to as I don't want it to close this issue) we need to do a PR to change instances of `setup-elixir` to `setup-beam`, this should be the limit of the scope.  Once this is merged in, we can rename the repo. 
 
 @wojtekmach had previously tested if checking the name of repo and/or action effects usage of existing releases and it seems no, it should be fine. Though, we should surely double check this and do whatever we can do ensure this is the case prior.  

If all this is good, then we can publish `setup-beam@v1`, once again operating under the assumption that `setup-elixir@v1` will continue to work as is.

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-26 10:00
Do you know, if `@v1` represents `@v1.x` or do we have to keep moving the tag up?

**Comment by starbelly** [comment] 2021-03-26 15:41
@paulo-ferraz-oliveira I would assume it does, but research required.

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-26 15:56
I'm asking especially since, at the moment, `v1` and `v1.6.0` are the same commit.

**Comment by starbelly** [comment] 2021-03-26 16:19
@paulo-ferraz-oliveira I think what we'll have to do is 
 
   - fork this
   - publish as setup-elixir under the name space of the fork as v1 (v1.6)
   - rename it
   - publish as setup-beam under the name of the fork as v1 (v1.7)
   - observe

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-26 18:11
Yeah, sorry, it was a sidetracking question[1]. I agree with your plan, though.

---

[1] Still am unable to understand how `@v1` is kept (@ericmj, is this tag manually moved?).

**Comment by starbelly** [comment] 2021-03-26 18:16
@paulo-ferraz-oliveira the way it works is you make a tag such as 1.6.0, you then reset v1 tag to the head of the new tag.

**Comment by ericmj** [comment] 2021-03-27 20:32
> I think what we'll have to do is [...]

Why do we need to do anything other than renaming?

> Still am unable to understand how @v1 is kept (@ericmj, is this tag manually moved?).

Yes.

**Comment by ericmj** [comment] 2021-03-27 20:32
Do we know if GitHub will keep the redirect forever from setup-elixir to setup-beam? If not, for how long will they redirect and what's the migration plan for users to the new action name?

**Comment by starbelly** [comment] 2021-03-27 20:50
> Why do we need to do anything other than renaming?

Theoretically, that should be fine if you mean just rename the repo and publish a new 1.x version, but I just thought we might want to be doubly sure we don't mess up builds.

> Do we know if GitHub will keep the redirect forever from setup-elixir to setup-beam? If not, for how long will they redirect and what's the migration plan for users to the new action name?

https://github.community/t/how-long-does-github-forward-renamed-moved-repos/582

@ericmj TL;DR is indefinitely.

**Comment by ericmj** [comment] 2021-03-27 20:52
> Theoretically, that should be fine if you mean just rename the repo and publish a new 1.x version, but I just thought we might want to be doubly sure we don't mess up builds.

What name are we going to use for the fork?

**Comment by wojtekmach** [comment] 2021-03-27 20:55
Im not sure a fork is necessary, I'd rename the repo to setup-beam, test it with another project, and in an very unlikely case it doesn't work, rename it back. After a few a day or two, make an announcement that setup-beam is the new repo.

**Comment by starbelly** [comment] 2021-03-27 21:06
> What name are we going to use for the fork?

@ericmj I would suggest something obscure, and not actually setup-elxir, especially for the publish

> Im not sure a fork is necessary, I'd rename the repo to setup-beam, test it with another project, and in an very unlikely case it doesn't work, rename it back. After a day or two, make an announcement that setup-beam is the new repo.

Maybe, but I don't know, production is always the real test. I'd rather be extra sure with a small investment (i.e., fork, publish, rename, publish) than to break a bunch of builds and deal with an onslaught of issues and slack messages. But to your point, maybe I'm overly concerned here.. but yeah, being sure is no bad thing especially at a cheap cost.

**Comment by ericmj** [comment] 2021-03-27 21:08
If the rename doesn't work the fork won't help since it's using a different name and if it doesn't work we can just rename it back. Or what am I missing?

**Comment by starbelly** [comment] 2021-03-27 21:11
> If the rename doesn't work the fork won't help since it's using a different name and if it doesn't work we can just rename it back. Or what am I missing?

Hmm what I'm suggesting is not doing the rename until after fork test is done, does that clarify?

**Comment by ericmj** [comment] 2021-03-27 21:17
> Hmm what I'm suggesting is not doing the rename until after fork test is done, does that clarify?

What are we testing with the fork?

**Comment by starbelly** [comment] 2021-03-27 21:26
> What are we testing with the fork?

After the a new repo is made with the contents of this repo and named something like `starbelly/lorem-ipsum-dolor-sit-amet` and AFTER the that is published as github action ( `starbelly/lorem-ipsum-dolor-sit-amet@v1`) we  can rename the repo to say `starbelly/ut-enim-ad-minim-veniam` AND publish the action as `starbelly/ut-enim-ad-minim-veniam@v1` that `starbelly/orem-ipsum-dolor-sit-amet` continue to work, and possibly further that the new rebar3 functionality works as well. 

All that said, if this is clearly documented some where in github that this should just work and we don't need to test it to be sure, then maybe not needed, but I saw no such documentation when I looked before and I myself just rather be sure. Like I said, the cost of doing so is just about nil, so I don't see why not.

**Comment by ericmj** [comment] 2021-03-27 21:30
> After the a new repo is made with the contents of this repo and named something like starbelly/lorem-ipsum-dolor-sit-amet and AFTER the that is published as github action ( starbelly/lorem-ipsum-dolor-sit-amet@v1) we can rename the repo to say starbelly/ut-enim-ad-minim-veniam AND publish the action as starbelly/ut-enim-ad-minim-veniam@v1 that starbelly/lorem-ipsum-dolor-sit-amet continue to work, and possibly further that the new rebar3 functionality works as well.

I believe @wojtekmach already tested this and confirmed it to work. But nothing is blocking testing it again now so go ahead, we don't need to wait for anything to do a rename test on a separate repo.

**Comment by wojtekmach** [comment] 2021-03-27 21:31
yeah I've already performed a test like that but as they say: if you want something done right, do it yourself :)

**Comment by starbelly** [comment] 2021-03-27 21:32
@wojtekmach I didn't think you tried publishing? That's my focus is on. Publish, use, rename, publish again, use. But maybe you did?

**Comment by ericmj** [comment] 2021-03-27 21:34
There isn't really a publish process for actions, we just use a git reference which normally is a tag. So if it works with one tag it should work with all, regardless of when it was created.

Also note that the rename is not blocked by the PR https://github.com/erlef/setup-elixir/pull/9 being merged. In fact, we should wait a while with publishing v1.7 after merging so we can test the main branch on our own repos before publishing.

**Comment by starbelly** [comment] 2021-03-27 21:36
@ericmj That makes sense. I of course trust @wojtekmach too. I thought there was something "special" a "button" click :) 

With that said, you ready to rename then?

**Comment by wojtekmach** [comment] 2021-03-27 21:39
this is the test: https://github.com/wojtekmach/setup-elixir-bug/commit/5158312e6904dfa2cffc55586febcde031c54b98. I've named wojtekmach/beamup2 to wojtekmach/beamup and that workflow continued to work after the rename.

**Comment by ericmj** [comment] 2021-03-27 21:41
> With that said, you ready to rename then?

We should have a PR ready with changes to the README and other places that references the name. Personally I would wait until the work week with doing the rename in case any support or quick fixes are needed, but that's up to you of course.

**Comment by starbelly** [comment] 2021-03-27 21:42
@ericmj hmm yeah, let me do that real quick.

**Comment by starbelly** [comment] 2021-03-27 21:43
@paulo-ferraz-oliveira You'll have a few merge conflicts to deal with, hate that the cookie crumbles that way, but @ericmj is right, this should happen first.

**Comment by starbelly** [comment] 2021-03-27 21:47
> Personally I would wait until the work week with doing the rename in case any support or quick fixes are needed, but that's up to you of course.

Hmm you would wait until say Tuesday? Rationale being better to blow up in the week vs a big surprise on monday?

**Comment by starbelly** [comment] 2021-03-27 21:58
> > Personally I would wait until the work week with doing the rename in case any support or quick fixes are needed, but that's up to you of course.
> 
> Hmm you would wait until say Tuesday? Rationale being better to blow up in the week vs a big surprise on monday?

Ahh n/m your concern is about doing work on the weekend. Yeah, that makes sense.

**Comment by paulo-ferraz-oliveira** [comment] 2021-03-27 23:03
Merge conflicts do not present an issue, at this moment. Your changes are very small in comparison to #9.

**Closed** 2021-03-29 19:51 UTC

**Comment by starbelly** [comment] 2021-03-29 20:01
Just to note : existing projects using setup-elixir should not be affected (tested with erlef website).
